services:
  web:
    build: .
    command: >
      bash -lc "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    env_file: .env
    volumes:
      - .:/app                  # código montado -> hot-reload do Django
      - ./data:/app/data        # (sqlite) db.sqlite3, -wal, -shm
      - staticfiles:/app/staticfiles
      - media:/app/media
    ports:
      - "8000:8000"

volumes:
  staticfiles:
  media: