# Generated by Django 5.2.6 on 2025-09-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Entre o nome', max_length=100)),
                ('curso', models.CharField(help_text='Entre o curso', max_length=100)),
                ('periodo', models.IntegerField(help_text='Informe o período do curso')),
                ('email', models.EmailField(help_text='Informe o email', max_length=254)),
                ('vitorias', models.IntegerField(help_text='Número de vitórias')),
                ('derrotas', models.IntegerField(help_text='Número de derrotas')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='jogadores/')),
                ('dtNasc', models.DateField(help_text='Nascimento no formato DD/MM/AAAA', verbose_name='Data de nascimento')),
            ],
        ),
    ]
