# Generated by Django 5.2.6 on 2025-10-03 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="jogador",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Usuário associado a este jogador (opcional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jogador",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="jogador",
            name="curso",
            field=models.CharField(
                blank=True, default="", help_text="Entre o curso", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="jogador",
            name="derrotas",
            field=models.IntegerField(default=0, help_text="Número de derrotas"),
        ),
        migrations.AlterField(
            model_name="jogador",
            name="dtNasc",
            field=models.DateField(
                blank=True,
                help_text="Nascimento no formato DD/MM/AAAA",
                null=True,
                verbose_name="Data de nascimento",
            ),
        ),
        migrations.AlterField(
            model_name="jogador",
            name="email",
            field=models.EmailField(
                blank=True, default="", help_text="Informe o email", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="jogador",
            name="nome",
            field=models.CharField(
                blank=True, default="", help_text="Entre o nome", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="jogador",
            name="periodo",
            field=models.IntegerField(
                default=0, help_text="Informe o período do curso"
            ),
        ),
        migrations.AlterField(
            model_name="jogador",
            name="vitorias",
            field=models.IntegerField(default=0, help_text="Número de vitórias"),
        ),
        migrations.CreateModel(
            name="Partida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField(auto_now_add=True)),
                ("pontos", models.IntegerField(default=0)),
                (
                    "jogador1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidas_jogador1",
                        to="core.jogador",
                    ),
                ),
                (
                    "jogador2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidas_jogador2",
                        to="core.jogador",
                    ),
                ),
                (
                    "perdedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derrotas_partidas",
                        to="core.jogador",
                    ),
                ),
                (
                    "vencedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitorias_partidas",
                        to="core.jogador",
                    ),
                ),
            ],
        ),
    ]
